Create mock ach bank account
circlefin/payments-sample-app pull request #101
Opened 2020-12-23 06:46 UTC by timmy-circle

Add support to create mock ACH bank account with specified balance.

2021-01-05 20:18 UTC, huaweigu commented on pages/debug/ach/mocks/create.vue
> +            label="ACH Account Number"
should make this and following fields required

2021-01-05 20:18 UTC, huaweigu commented on pages/debug/payouts/index.vue
> +            Create or update a mock ACH bank account
Does the mock endpoint support update?

2021-01-05 20:20 UTC, timmy-circle commented on pages/debug/payouts/index.vue
> +            Create or update a mock ACH bank account
oh good catch. No update

2021-01-05 20:21 UTC, timmy-circle commented on pages/debug/ach/mocks/create.vue
> +            label="ACH Account Number"
I remember chatting with @kristinfritsch that we shouldn't be adding restriction/validation on UI?

2021-01-05 20:29 UTC, huaweigu commented on pages/debug/ach/mocks/create.vue
> +            label="ACH Account Number"
okay, not sure if we can enforce some rules in the class, also could at least do a `hint` (prompt xxx is required)

2021-01-06 12:43 UTC, kristinfritsch requested changes
Small comments, otherwise looks good

2021-01-06 12:43 UTC, kristinfritsch commented on pages/debug/ach/mocks/create.vue
> +            label="ACH Account Number"
The reason we don't want to put restrictions on the UI is do make testing of edge cases easier (e.g. error cases of the api). That doesn't really apply to mock apis. I think it's fine to make these fields required if needed.

2021-01-06 12:43 UTC, kristinfritsch commented on pages/debug/ach/mocks/create.vue
> +            depressed
This really should only be enabled for sandbox. We hide that button for on the mock wire page `/debug/payments/mocks/wire`. I don't think that's the best solution, but that's the pattern right now, so let's keep it.

2021-01-06 14:26 UTC, timmy-circle commented on pages/debug/ach/mocks/create.vue
> +            label="ACH Account Number"
okie. Will update.

2021-01-07 00:44 UTC, timmy-circle commented on pages/debug/ach/mocks/create.vue
> +            depressed
addressed.

2021-01-07 01:01 UTC, huaweigu approved these changes
lgtm

2021-01-07 01:49 UTC, MasterXen approved these changes

2021-01-07 01:51 UTC, merged