[BRAAV-3751] Add page for /returns endpoint.
circlefin/payments-sample-app pull request #108
Opened 2021-02-15 13:47 UTC by pkennedy-circle

The sample app page for the returns endpoint.

The endpoint itself was added in this txcore PR: https://github.com/circlefin/transaction-core/pull/7467

**Story:** https://circlepay.atlassian.net/browse/BRAAV-3751

2021-02-15 14:15 UTC, kristinfritsch commented on layouts/default.vue
> +      to: '/debug/payouts/returns/fetch',
Can we move this up, below `title: 'GET /payouts/{id}'` please

2021-02-15 14:15 UTC, kristinfritsch commented on pages/debug/index.vue
> +      <v-card class="body-1 px-6 py-8 mb-4" max-width="800" outlined>
This belongs to the payouts section below.

2021-02-15 14:31 UTC, pkennedy-circle commented on pages/debug/index.vue
> +      <v-card class="body-1 px-6 py-8 mb-4" max-width="800" outlined>
I've moved this card down. Just wanted to confirm that this should be its own card, similar to what was done with `/reversals`.

2021-02-15 17:30 UTC, geehsien commented on layouts/default.vue
> +      to: '/debug/payouts/returns/fetch',
Agree here -- also, if it's the case that we didn't add a sample app endpoint for `/v1/reversals` previously, could we file a jira story to add that as a follow up?

2021-02-15 17:44 UTC, kristinfritsch commented on layouts/default.vue
> +      to: '/debug/payouts/returns/fetch',
Sorry that i made you make these changes. I thought the endpoint can be found under `v1/payouts/returns`, but it's just `v1/payouts`. So i think you were right in the first place.

2021-02-15 17:47 UTC, kristinfritsch commented
One thought I had. Should the reversals page be under `/debug/reversals/fetch` and the returns under `/debug/returns/fetch`? Just to follow the pattern we have for the other pages.

2021-02-15 17:51 UTC, pkennedy-circle commented on layouts/default.vue
> +      to: '/debug/payouts/returns/fetch',
Hi @geehsien, the reversals endpoint is already up and available here: 
https://sample-sandbox.circle.com/debug/payments/reversals/fetch
As you can see on the sidebar, it's been placed towards the bottom of the `Payments` section.

Let me know if you'd like me to place both returns and reversals links near the top of their sidebars, or if we're happy adding them to the bottom.

2021-02-15 17:51 UTC, pkennedy-circle commented
> One thought I had. Should the reversals page be under `/debug/reversals/fetch` and the returns under `/debug/returns/fetch`? Just to follow the pattern we have for the other pages.

That makes sense to me - I'll make that change.

2021-02-15 18:05 UTC, geehsien commented on layouts/default.vue
> +      to: '/debug/payouts/returns/fetch',
Ah you're right @pkennedy-circle -- I was confused and was looking for it under the Payouts section. 😆 

Thanks for pointing that out. I think the location of `reversals` is fine as-is. 

Thinking more about this and @kristinfritsch's updated comment, I think the original location (beneath transfers) is good.

When we get to the documentation, I think the same location (below Payouts, Bank accounts, and Transfers) will be good as well.

2021-02-15 18:09 UTC, pkennedy-circle commented on layouts/default.vue
> +      to: '/debug/payouts/returns/fetch',
No worries! Thanks for the feedback :)

2021-02-16 11:52 UTC, kristinfritsch commented on pages/debug/index.vue
> +      <v-card class="body-1 px-6 py-8 mb-4" max-width="800" outlined>
Yeah let's match what we have for reversals, thanks

2021-02-16 12:05 UTC, kristinfritsch requested changes

2021-02-16 12:05 UTC, kristinfritsch commented on pages/debug/index.vue
> +      <v-card class="body-1 px-6 py-8 mb-4" max-width="800" outlined>
Does this need to go under `/debug/payouts/index.vue` instead of `debug/index.vue` ?

2021-02-16 12:05 UTC, kristinfritsch commented on pages/debug/index.vue
> +        <p>Api endpoints to manage returns.</p>
Looking for a better description here: `Api endpoints to retrieve a list of ACH payout returns`. (You tell me if that's correct ;))

2021-02-16 12:05 UTC, kristinfritsch commented on pages/debug/index.vue
> +        <p>Api endpoints to manage returns.</p>
On the same note. We can add: `Retrieve a list of ACH payment reversals.` for the `/reversals` endpoint. What do you think?

2021-02-16 17:12 UTC, pkennedy-circle commented on pages/debug/index.vue
> +      <v-card class="body-1 px-6 py-8 mb-4" max-width="800" outlined>
Thanks for catching that, I made the change there 👍

2021-02-16 17:29 UTC, kristinfritsch approved these changes

2021-02-19 09:28 UTC, jcantwell approved these changes

2021-02-19 09:28 UTC, merged