Apple Pay in Staging
circlefin/payments-sample-app pull request #160
Opened 2022-02-16 13:15 UTC by antiv0

2022-02-17 07:40 UTC, antiv0 commented on server-middleware/applepay.ts
> +} from './applePaySecrets'
Server middleware is loaded by Node, so used relative paths (couldn't use @/..)
 If there is a way to make it nicer ?

2022-02-17 09:02 UTC, antiv0 commented on lib/applePay.ts
> +    product_price: '0.5',
Price $0.5 for testing hardcoded (didn't want to involve forms and stuff until we see that apple pay can work end to end + until we have UI expectations)

2022-02-17 11:01 UTC, kristinfritsch requested changes

2022-02-17 11:02 UTC, kristinfritsch commented
If i call `http://localhost:3011/applepay/pay` i get page not found

2022-02-17 11:12 UTC, antiv0 commented on server-middleware/applePaySecrets.ts
> +  ? process.env.apple_pay_certifcate!
Thank you !!

2022-02-17 11:20 UTC, antiv0 commented on layouts/default.vue
> +  getPaymentLinks() {
sure,
// i do get that `get` names a property/attribute, like in C#
// changing method to property

2022-02-17 11:43 UTC, antiv0 commented
> If i call `http://localhost:3011/applepay/pay` i get page not found, doesn't seem right

curl -X POST -H "Content-Type: application/json" http://192.168.1.6:3011/applepay/pay -d '{}'

2022-02-17 11:57 UTC, kristinfritsch commented on lib/applePay.ts
> +  'https://sample-staging.circle.com/applepay/validate'
can it be configurable via env var

2022-02-18 10:51 UTC, kristinfritsch submitted a review, later dismissed

2022-02-18 15:47 UTC, kristinfritsch approved these changes

2022-02-18 15:59 UTC, merged